import { ImportTableData } from "./ImportsTable";

export const originData: ImportTableData[] = [
  {
    key: "1",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "2",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Actual",
    importDate: "24/10/2023",
  },
  {
    key: "3",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "24/10/2023",
  },
  {
    key: "4",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "5",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Actual",
    importDate: "24/10/2023",
  },
  {
    key: "6",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "24/10/2023",
  },
  {
    key: "7",
    category: "Electricity",
    cnCode: "2716 00 00",
    operator: "XYZ Company",
    volume: "300 MW",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "8",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Actual",
    importDate: "17/10/2023",
  },
  {
    key: "9",
    category: "Electricity",
    cnCode: "2716 00 00",
    operator: "XYZ Company",
    volume: "300 MW",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "10",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "11",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Actual",
    importDate: "24/10/2023",
  },
  {
    key: "12",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "24/10/2023",
  },
  {
    key: "13",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "14",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Actual",
    importDate: "24/10/2023",
  },
  {
    key: "15",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "24/10/2023",
  },
  {
    key: "16",
    category: "Electricity",
    cnCode: "2716 00 00",
    operator: "XYZ Company",
    volume: "300 MW",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "17",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Actual",
    importDate: "17/10/2023",
  },
  {
    key: "18",
    category: "Electricity",
    cnCode: "2716 00 00",
    operator: "XYZ Company",
    volume: "300 MW",
    emissions: "30 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "19",
    category: "Cement",
    cnCode: "2523 10 00",
    operator: "kolumbus Ltd.",
    volume: "100 t",
    emissions: "10 tCO2e",
    calculationMethod: "Default",
    importDate: "17/10/2023",
  },
  {
    key: "20",
    category: "Aluminium",
    cnCode: "7601",
    operator: "ABC Company",
    volume: "200 t",
    emissions: "30 tCO2e",
    calculationMethod: "Actual",
    importDate: "24/10/2023",
  },
];
