import { Item } from "./ReportsTable";

export const originData: Item[] = [
  {
    key: "4",
    name: "kolumbus Ltd.",
    city: "City D",
    country: "Country D",
    imported_good: "New Imported Good D",
    Production_installation: "City D, Country D",
    Phone_number: "1234567803",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123462",
    portalId: 999993,
    streetName: "New Street D",
    streetNumber: "4",
    zip: 11105,
    poBox: "PO993",
    Id: "RPT004",
    quarter: "Q3/2023",
    createdAt: "2023-03-15",
    lastUpdated: "2023-03-16",
    createdBy: "Charlie Davis",
    status: "Rejected",
    file: "/path/to/file3.pdf",
  },
  {
    key: "5",
    name: "ABC Company",
    city: "City E",
    country: "Country E",
    imported_good: "New Imported Good E",
    Production_installation: "City E, Country E",
    Phone_number: "1234567804",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123463",
    portalId: 999992,
    streetName: "New Street E",
    streetNumber: "5",
    zip: 11104,
    poBox: "PO992",
    Id: "RPT005",
    quarter: "Q4/2022",
    createdAt: "2022-12-10",
    lastUpdated: "2022-12-11",
    createdBy: "Emma Evans",
    status: "Rejected",
    file: "/path/to/file4.pdf",
  },
  {
    key: "6",
    name: "New Company F",
    city: "City F",
    country: "Country F",
    imported_good: "New Imported Good F",
    Production_installation: "City F, Country F",
    Phone_number: "1234567805",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123464",
    portalId: 999991,
    streetName: "New Street F",
    streetNumber: "6",
    zip: 11103,
    poBox: "PO991",
    Id: "RPT006",
    quarter: "Q1/2023",
    createdAt: "2023-01-20",
    lastUpdated: "2023-01-21",
    createdBy: "John Johnson",
    status: "Approved",
    file: "/path/to/file5.pdf",
  },
  {
    key: "7",
    name: "New Company G",
    city: "City G",
    country: "Country G",
    imported_good: "New Imported Good G",
    Production_installation: "City G, Country G",
    Phone_number: "1234567806",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123465",
    portalId: 999990,
    streetName: "New Street G",
    streetNumber: "7",
    zip: 11102,
    poBox: "PO990",
    Id: "RPT007",
    quarter: "Q2/2022",
    createdAt: "2022-06-05",
    lastUpdated: "2022-06-06",
    createdBy: "Sophia Smith",
    status: "Rejected",
    file: "/path/to/file6.pdf",
  },
  {
    key: "8",
    name: "New Company H",
    city: "City H",
    country: "Country H",
    imported_good: "New Imported Good H",
    Production_installation: "City H, Country H",
    Phone_number: "1234567807",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123466",
    portalId: 999989,
    streetName: "New Street H",
    streetNumber: "8",
    zip: 11101,
    poBox: "PO989",
    Id: "RPT008",
    quarter: "Q3/2022",
    createdAt: "2022-09-15",
    lastUpdated: "2022-09-16",
    createdBy: "Daniel Davis",
    status: "Approved",
    file: "/path/to/file7.pdf",
  },
  {
    key: "9",
    name: "New Company I",
    city: "City I",
    country: "Country I",
    imported_good: "New Imported Good I",
    Production_installation: "City I, Country I",
    Phone_number: "1234567808",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123467",
    portalId: 999988,
    streetName: "New Street I",
    streetNumber: "9",
    zip: 11109,
    poBox: "PO988",
    Id: "RPT009",
    quarter: "Q4/2023",
    createdAt: "2023-02-28",
    lastUpdated: "2023-03-01",
    createdBy: "Olivia Owens",
    status: "Rejected",
    file: "/path/to/file8.pdf",
  },
  {
    key: "10",
    name: "New Company J",
    city: "City J",
    country: "Country J",
    imported_good: "New Imported Good J",
    Production_installation: "City J, Country J",
    Phone_number: "1234567809",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123468",
    portalId: 999987,
    streetName: "New Street J",
    streetNumber: "10",
    zip: 11108,
    poBox: "PO987",
    Id: "RPT010",
    quarter: "Q1/2023",
    createdAt: "2023-01-05",
    lastUpdated: "2023-01-06",
    createdBy: "Liam Lee",
    status: "Rejected",
    file: "/path/to/file9.pdf",
  },
  {
    key: "11",
    name: "New Company K",
    city: "City K",
    country: "Country K",
    imported_good: "New Imported Good K",
    Production_installation: "City K, Country K",
    Phone_number: "1234567810",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123469",
    portalId: 999986,
    streetName: "New Street K",
    streetNumber: "11",
    zip: 11107,
    poBox: "PO986",
    Id: "RPT011",
    quarter: "Q2/2022",
    createdAt: "2022-04-10",
    lastUpdated: "2022-04-11",
    createdBy: "Ava Adams",
    status: "Approved",
    file: "/path/to/file10.pdf",
  },
  {
    key: "12",
    name: "kolum.earth, Inc.",
    city: "City L",
    country: "XYZ Company",
    imported_good: "New Imported Good L",
    Production_installation: "City L, Country L",
    Phone_number: "1234567811",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123470",
    portalId: 999985,
    streetName: "New Street L",
    streetNumber: "12",
    zip: 11106,
    poBox: "PO985",
    Id: "RPT012",
    quarter: "Q3/2022",
    createdAt: "2022-08-15",
    lastUpdated: "2022-08-16",
    createdBy: "Mia Miller",
    status: "Pending",
    file: "/path/to/file11.pdf",
  },
  {
    key: "13",
    name: "New Company M",
    city: "Another Company",
    country: "Country M",
    imported_good: "New Imported Good M",
    Production_installation: "City M, Country M",
    Phone_number: "1234567812",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123471",
    portalId: 999984,
    streetName: "New Street M",
    streetNumber: "13",
    zip: 11105,
    poBox: "PO984",
    Id: "RPT013",
    quarter: "Q4/2023",
    createdAt: "2023-03-01",
    lastUpdated: "2023-03-02",
    createdBy: "Noah Nelson",
    status: "Approved",
    file: "/path/to/file12.pdf",
  },
  {
    key: "14",
    name: "Global Exports",
    city: "City N",
    country: "kolum.earth, Inc.",
    imported_good: "New Imported Good N",
    Production_installation: "City N, Country N",
    Phone_number: "1234567813",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123472",
    portalId: 999983,
    streetName: "New Street N",
    streetNumber: "14",
    zip: 11104,
    poBox: "PO983",
    Id: "RPT014",
    quarter: "Q1/2023",
    createdAt: "2023-01-10",
    lastUpdated: "2023-01-11",
    createdBy: "Ethan Evans",
    status: "Pending",
    file: "/path/to/file13.pdf",
  },
  {
    key: "15",
    name: "Trade Co.",
    city: "City O",
    country: "Country O",
    imported_good: "New Imported Good O",
    Production_installation: "City O, Country O",
    Phone_number: "1234567814",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123473",
    portalId: 999982,
    streetName: "New Street O",
    streetNumber: "15",
    zip: 11103,
    poBox: "PO982",
    Id: "RPT015",
    quarter: "Q2/2022",
    createdAt: "2022-05-15",
    lastUpdated: "2022-05-16",
    createdBy: "Luna Lee",
    status: "Approved",
    file: "/path/to/file14.pdf",
  },
  {
    key: "16",
    name: "Tech Innovations",
    city: "City P",
    country: "Country P",
    imported_good: "New Imported Good P",
    Production_installation: "City P, Country P",
    Phone_number: "1234567815",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123474",
    portalId: 999981,
    streetName: "New Street P",
    streetNumber: "16",
    zip: 11102,
    poBox: "PO981",
    Id: "RPT016",
    quarter: "Q3/2022",
    createdAt: "2022-09-01",
    lastUpdated: "2022-09-02",
    createdBy: "Logan Lopez",
    status: "Pending",
    file: "/path/to/file15.pdf",
  },
  {
    key: "17",
    name: "New Company Q",
    city: "City Q",
    country: "Country Q",
    imported_good: "New Imported Good Q",
    Production_installation: "City Q, Country Q",
    Phone_number: "1234567816",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123475",
    portalId: 999980,
    streetName: "New Street Q",
    streetNumber: "17",
    zip: 11101,
    poBox: "PO980",
    Id: "RPT017",
    quarter: "Q4/2023",
    createdAt: "2023-02-15",
    lastUpdated: "2023-02-16",
    createdBy: "Zoe Zimmerman",
    status: "Approved",
    file: "/path/to/file16.pdf",
  },
  {
    key: "18",
    name: "New Company R",
    city: "City R",
    country: "Country R",
    imported_good: "New Imported Good R",
    Production_installation: "City R, Country R",
    Phone_number: "1234567817",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123476",
    portalId: 999979,
    streetName: "New Street R",
    streetNumber: "18",
    zip: 11109,
    poBox: "PO979",
    Id: "RPT018",
    quarter: "Q1/2023",
    createdAt: "2023-01-01",
    lastUpdated: "2023-01-02",
    createdBy: "Nathan Newton",
    status: "Approved",
    file: "/path/to/file17.pdf",
  },
  {
    key: "19",
    name: "New Company S",
    city: "City S",
    country: "Country S",
    imported_good: "New Imported Good S",
    Production_installation: "City S, Country S",
    Phone_number: "1234567818",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123477",
    portalId: 999978,
    streetName: "New Street S",
    streetNumber: "19",
    zip: 11108,
    poBox: "PO978",
    Id: "RPT019",
    quarter: "Q2/2022",
    createdAt: "2022-03-10",
    lastUpdated: "2022-03-11",
    createdBy: "Victoria Vance",
    status: "Approved",
    file: "/path/to/file18.pdf",
  },
  {
    key: "20",
    name: "New Company T",
    city: "City T",
    country: "Country T",
    imported_good: "New Imported Good T",
    Production_installation: "City T, Country T",
    Phone_number: "1234567819",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "AB123478",
    portalId: 999977,
    streetName: "New Street T",
    streetNumber: "20",
    zip: 11107,
    poBox: "PO977",
    Id: "RPT020",
    quarter: "Q3/2022",
    createdAt: "2022-07-20",
    lastUpdated: "2022-07-21",
    createdBy: "Gabriel Garcia",
    status: "Approved",
    file: "/path/to/file19.pdf",
  },
];
