import { Item } from "./OperatorsTable";

export const originData: Item[] = [
  {
    key: "1",
    name: "kolum.earth Inc.",
    city: "New York City",
    country: "USA",
    imported_good: [
      "2507 00 80 – Other kaolinic clays",
      "2323 10 10 - Cement clinkers",
    ],
    Production_installation: ["New York City, USA", "Beijing, China"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "DE123456",
    operatorId: 123456,
    streetName: "Kolum Street",
    streetNumber: "1",
    zip: 12345,
    poBox: "PO123",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
  },
  {
    key: "2",
    name: "Another Company",
    city: "Beijing",
    country: "China",
    imported_good: ["Some Imported Good"],
    Production_installation: ["Beijing, China"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "CN789012",
    operatorId: 987654,
    streetName: "Main Street",
    streetNumber: "2",
    zip: 54321,
    poBox: "PO987",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
  },
  {
    key: "3",
    name: "ABC Corporation",
    city: "Los Angeles",
    country: "USA",
    imported_good: [
      "3304 20 00 – Mixtures of rock lobster and other sea crawfish",
      "7103 99 00 – Precious stones",
    ],
    Production_installation: ["Los Angeles, USA"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "US567890",
    operatorId: 567890,
    streetName: "Ocean Avenue",
    streetNumber: "3",
    zip: 67890,
    poBox: "PO345",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
  },
  {
    key: "4",
    name: "XYZ Ltd.",
    city: "London",
    country: "UK",
    imported_good: [
      "4820 30 00 – Cigarette paper",
      "8418 21 00 – Refrigerators",
    ],
    Production_installation: ["London, UK"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "UK234567",
    operatorId: 234567,
    streetName: "London Street",
    streetNumber: "4",
    zip: 23456,
    poBox: "PO678",
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.williams@example.com",
  },
  {
    key: "5",
    name: "Global Exports",
    city: "Mumbai",
    country: "India",
    imported_good: [
      "7103 99 00 – Precious stones",
      "8542 31 00 – Microprocessors",
    ],
    Production_installation: ["Mumbai, India"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "IN789012",
    operatorId: 789012,
    streetName: "Gems Street",
    streetNumber: "5",
    zip: 34567,
    poBox: "PO123",
    firstName: "David",
    lastName: "Jones",
    email: "david.jones@example.com",
  },
  {
    key: "6",
    name: "Trade Co.",
    city: "Paris",
    country: "France",
    imported_good: [
      "8418 21 00 – Refrigerators",
      "6204 43 00 – Women's dresses",
    ],
    Production_installation: ["Paris, France", "Berlin, Germany"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "FR234567",
    operatorId: 123456,
    streetName: "Avenue de Paris",
    streetNumber: "6",
    zip: 45678,
    poBox: "PO987",
    firstName: "Sophie",
    lastName: "Martin",
    email: "sophie.martin@example.com",
  },
  {
    key: "7",
    name: "Tech Innovations",
    city: "San Francisco",
    country: "USA",
    imported_good: [
      "8542 31 00 – Microprocessors",
      "8528 72 00 – Video game consoles",
    ],
    Production_installation: ["San Francisco, USA", "Tokyo, Japan"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "US123456",
    operatorId: 567890,
    streetName: "Innovation Street",
    streetNumber: "7",
    zip: 56789,
    poBox: "PO345",
    firstName: "Daniel",
    lastName: "Lee",
    email: "daniel.lee@example.com",
  },
  {
    key: "8",
    name: "Euro Fashion",
    city: "Berlin",
    country: "Germany",
    imported_good: [
      "6204 43 00 – Women's dresses",
      "2323 10 10 - Cement clinkers",
    ],
    Production_installation: ["Berlin, Germany"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "DE234567",
    operatorId: 234567,
    streetName: "Fashion Street",
    streetNumber: "8",
    zip: 45678,
    poBox: "PO123",
    firstName: "Sophia",
    lastName: "Schmidt",
    email: "sophia.schmidt@example.com",
  },
  {
    key: "9",
    name: "Sunrise Electronics",
    city: "Tokyo",
    country: "Japan",
    imported_good: [
      "8528 72 00 – Video game consoles",
      "2507 00 80 – Other kaolinic clays",
    ],
    Production_installation: ["Tokyo, Japan"],
    Phone_number: "727349732492",
    editable: true,
    dataIndex: "name",
    title: "Name",
    eori: "JP345678",
    operatorId: 345678,
    streetName: "Electronics Avenue",
    streetNumber: "9",
    zip: 23456,
    poBox: "PO112",
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki.tanaka@example.com",
  },
];
