import { Item } from "./OperatorsTable";

export const originData: Item[] = [
  {
    key: "1",
    name: "kolum.earth Inc.",
    city: "New York City",
    country: "USA",
    imported_good: "2507 00 80 – Other kaolinic clays",
    Production_installation: "New York City, USA",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "2",
    name: "Another Company",
    city: "Beijing",
    country: "China",
    imported_good: "Some Imported Good",
    Production_installation: "Beijing, China",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "3",
    name: "ABC Corporation",
    city: "Los Angeles",
    country: "USA",
    imported_good:
      "3304 20 00 – Mixtures of rock lobster and other sea crawfish",
    Production_installation: "Los Angeles, USA",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "4",
    name: "XYZ Ltd.",
    city: "London",
    country: "UK",
    imported_good: "4820 30 00 – Cigarette paper",
    Production_installation: "London, UK",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "5",
    name: "Global Exports",
    city: "Mumbai",
    country: "India",
    imported_good: "7103 99 00 – Precious stones",
    Production_installation: "Mumbai, India",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "6",
    name: "Trade Co.",
    city: "Paris",
    country: "France",
    imported_good: "8418 21 00 – Refrigerators",
    Production_installation: "Paris, France",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "7",
    name: "Tech Innovations",
    city: "San Francisco",
    country: "USA",
    imported_good: "8542 31 00 – Microprocessors",
    Production_installation: "San Francisco, USA",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "8",
    name: "Euro Fashion",
    city: "Berlin",
    country: "Germany",
    imported_good: "6204 43 00 – Women's dresses",
    Production_installation: "Berlin, Germany",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "9",
    name: "Sunrise Electronics",
    city: "Tokyo",
    country: "Japan",
    imported_good: "8528 72 00 – Video game consoles",
    Production_installation: "Tokyo, Japan",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "10",
    name: "Food & Flavors",
    city: "Rome",
    country: "Italy",
    imported_good: "2106 90 99 – Food preparations",
    Production_installation: "Rome, Italy",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "11",
    name: "AquaTech",
    city: "Sydney",
    country: "Australia",
    imported_good: "9506 11 00 – Water sports equipment",
    Production_installation: "Sydney, Australia",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "12",
    name: "Green Energy Ltd.",
    city: "Vancouver",
    country: "Canada",
    imported_good: "8410 19 00 – Solar panels",
    Production_installation: "Vancouver, Canada",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "13",
    name: "Nature's Bounty",
    city: "Rio de Janeiro",
    country: "Brazil",
    imported_good: "1211 90 99 – Natural products",
    Production_installation: "Rio de Janeiro, Brazil",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "14",
    name: "Gadget World",
    city: "Seoul",
    country: "South Korea",
    imported_good: "8703 24 00 – Smartphones",
    Production_installation: "Seoul, South Korea",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "15",
    name: "FashionHub",
    city: "Paris",
    country: "France",
    imported_good: "6205 20 00 – Men's suits",
    Production_installation: "Paris, France",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "16",
    name: "GreenTech Solutions",
    city: "Amsterdam",
    country: "Netherlands",
    imported_good: "9405 10 00 – LED lighting",
    Production_installation: "Amsterdam, Netherlands",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "17",
    name: "AutoMasters",
    city: "Detroit",
    country: "USA",
    imported_good: "8708 30 00 – Car engines",
    Production_installation: "Detroit, USA",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "18",
    name: "HealthCare Innovations",
    city: "Singapore",
    country: "Singapore",
    imported_good: "9018 12 00 – Medical devices",
    Production_installation: "Singapore, Singapore",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "19",
    name: "TechGear Inc.",
    city: "San Jose",
    country: "USA",
    imported_good: "8517 12 00 – Mobile phones",
    Production_installation: "San Jose, USA",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
  {
    key: "20",
    name: "Agriculture Solutions",
    city: "Buenos Aires",
    country: "Argentina",
    imported_good: "0703 10 00 – Onions",
    Production_installation: "Buenos Aires, Argentina",
    editable: true,
    dataIndex: "name",
    title: "Name",
  },
];
